#include "tests/common.h"

#include <QCoreApplication>
#include <iostream>

void test_qt_sse_parser_reads_multiline_data();
void test_qt_sse_parser_reads_retry();
void test_qt_sse_parser_reads_crlf_events();
void test_qt_transport_constructs();
void test_qt_transport_shutdown_is_idempotent();
void test_qt_transport_rejects_send_before_start();
void test_qt_transport_keeps_core_session_api_shape();
void test_qt_transport_updates_protocol_version_runtime();
void test_qt_transport_auth_retry();
void test_qt_transport_post_event_stream_parsing();
void test_qt_transport_post_json_with_data_field();
void test_qt_transport_auth_retry_failure_stops_reconnect();
void test_qt_transport_updates_token_provider_runtime();
void test_qt_transport_post_auth_failure_blocks_message();
void test_qt_connect_stdio_integration();
void test_qt_http_request_config();
void test_qt_typed_results();
void test_qt_resource_router();
void test_qt_tools_model();
void test_qt_transport_recovery();
void test_qt_server_manager_router();
void test_qt_stateless_http_transport_basic();
void test_qt_stateless_http_transport_headers();
void test_qt_stateless_http_transport_trace_headers();
void test_multi_server_agent_diagnostics_groups_entries_by_stage();
void test_multi_agent_registry_union_and_reverse();
void test_multi_agent_reconciler_enables_union();
void test_qt_stateless_session_meta_injection();
void test_qt_stateless_session_mrtr_loop();
void test_qt_stateless_session_multi_round_mrtr_loop();
void test_qt_stateless_session_log_level();
void test_qt_highlevel_builder_and_signals();
void test_qt_tasks_capability_declaration();
void test_qt_tasks_get_wire_and_parse();
void test_qt_tasks_update_cancel_wire();
void test_qt_tasks_notifications();
void test_qt_tasks_calltool_transparent_poll();
void test_qt_tasks_calltool_task_handle();
void test_qt_tasks_sync_apis();
void test_qt_server_view_filtering();
void test_qt_server_view_multi_view_isolation();
void test_qt_server_view_schema_export();
void test_qt_mcp_app_bridge_initialize();
void test_qt_mcp_app_bridge_tools_list_filter();
void test_qt_mcp_app_bridge_tools_call_permission_denied();
void test_qt_mcp_app_bridge_tools_call_success();
void test_qt_mcp_app_bridge_open_link();
void test_qt_mcp_app_bridge_unknown_method();
void test_qt_mcp_app_bridge_tools_call_visibility_denied();
void test_mcp_app_support_csp_construction();
void test_mcp_app_support_allow_attribute();
void test_qt_mcp_app_bridge_initialized_gate();
void test_qt_mcp_app_bridge_size_changed();
void test_qt_mcp_app_bridge_host_context_full();
void test_qt_mcp_app_bridge_display_mode_negotiation();
void test_qt_mcp_app_bridge_app_log_signal();
void test_qt_mcp_app_bridge_teardown_waits_response();
void test_qt_mcp_app_bridge_teardown_timeout();
void test_mcp_app_support_ui_meta_helpers();
void test_mcp_app_content_adapter_registry_is_generic();
void test_mcp_app_cesium_adapter_is_isolated_and_declares_csp();
void test_es256_jwt_derive_public_key_matches_rfc6979();
void test_es256_jwt_pkcs8_build_and_verify();
void test_es256_jwt_sec1_build_and_verify();
void test_es256_jwt_tamper_detected();
void test_es256_jwt_invalid_pem_rejected();
void test_es256_jwt_claims_times_and_jti();

int main(int argc, char* argv[]) {
    QCoreApplication app(argc, argv);

    TmTestRunner::instance().startTestSuite("Qt HttpSse Transport Tests");

    TM_RUN_TEST(test_qt_sse_parser_reads_multiline_data);
    TM_RUN_TEST(test_qt_sse_parser_reads_retry);
    TM_RUN_TEST(test_qt_sse_parser_reads_crlf_events);
    TM_RUN_TEST(test_qt_transport_constructs);
    TM_RUN_TEST(test_qt_transport_shutdown_is_idempotent);
    TM_RUN_TEST(test_qt_transport_rejects_send_before_start);
    TM_RUN_TEST(test_qt_transport_keeps_core_session_api_shape);
    TM_RUN_TEST(test_qt_transport_updates_protocol_version_runtime);
    TM_RUN_TEST(test_qt_transport_auth_retry);
    TM_RUN_TEST(test_qt_transport_post_event_stream_parsing);
    TM_RUN_TEST(test_qt_transport_post_json_with_data_field);
    TM_RUN_TEST(test_qt_transport_auth_retry_failure_stops_reconnect);
    TM_RUN_TEST(test_qt_transport_updates_token_provider_runtime);
    TM_RUN_TEST(test_qt_transport_post_auth_failure_blocks_message);
    // TM_RUN_TEST(test_qt_connect_stdio_integration);
    TM_RUN_TEST(test_qt_http_request_config);
    TM_RUN_TEST(test_qt_typed_results);
    TM_RUN_TEST(test_qt_resource_router);
    TM_RUN_TEST(test_qt_tools_model);
    TM_RUN_TEST(test_qt_transport_recovery);
    TM_RUN_TEST(test_qt_stateless_http_transport_basic);
    TM_RUN_TEST(test_qt_stateless_http_transport_headers);
    TM_RUN_TEST(test_qt_stateless_http_transport_trace_headers);
    TM_RUN_TEST(test_qt_server_manager_router);
    TM_RUN_TEST(test_multi_server_agent_diagnostics_groups_entries_by_stage);
    TM_RUN_TEST(test_multi_agent_registry_union_and_reverse);
    TM_RUN_TEST(test_multi_agent_reconciler_enables_union);
    TM_RUN_TEST(test_qt_stateless_session_meta_injection);
    TM_RUN_TEST(test_qt_stateless_session_mrtr_loop);
    TM_RUN_TEST(test_qt_stateless_session_multi_round_mrtr_loop);
    TM_RUN_TEST(test_qt_stateless_session_log_level);
    TM_RUN_TEST(test_qt_highlevel_builder_and_signals);
    TM_RUN_TEST(test_qt_tasks_capability_declaration);
    TM_RUN_TEST(test_qt_tasks_get_wire_and_parse);
    TM_RUN_TEST(test_qt_tasks_update_cancel_wire);
    TM_RUN_TEST(test_qt_tasks_notifications);
    TM_RUN_TEST(test_qt_tasks_calltool_transparent_poll);
    TM_RUN_TEST(test_qt_tasks_calltool_task_handle);
    TM_RUN_TEST(test_qt_tasks_sync_apis);
    TM_RUN_TEST(test_qt_server_view_filtering);
    TM_RUN_TEST(test_qt_server_view_multi_view_isolation);
    TM_RUN_TEST(test_qt_server_view_schema_export);
    TM_RUN_TEST(test_qt_mcp_app_bridge_initialize);
    TM_RUN_TEST(test_qt_mcp_app_bridge_tools_list_filter);
    TM_RUN_TEST(test_qt_mcp_app_bridge_tools_call_permission_denied);
    TM_RUN_TEST(test_qt_mcp_app_bridge_tools_call_success);
    TM_RUN_TEST(test_qt_mcp_app_bridge_open_link);
    TM_RUN_TEST(test_qt_mcp_app_bridge_unknown_method);
    TM_RUN_TEST(test_qt_mcp_app_bridge_tools_call_visibility_denied);
    TM_RUN_TEST(test_mcp_app_support_csp_construction);
    TM_RUN_TEST(test_mcp_app_support_allow_attribute);
    TM_RUN_TEST(test_qt_mcp_app_bridge_initialized_gate);
    TM_RUN_TEST(test_qt_mcp_app_bridge_size_changed);
    TM_RUN_TEST(test_qt_mcp_app_bridge_host_context_full);
    TM_RUN_TEST(test_qt_mcp_app_bridge_display_mode_negotiation);
    TM_RUN_TEST(test_qt_mcp_app_bridge_app_log_signal);
    TM_RUN_TEST(test_qt_mcp_app_bridge_teardown_waits_response);
    TM_RUN_TEST(test_qt_mcp_app_bridge_teardown_timeout);
    TM_RUN_TEST(test_mcp_app_support_ui_meta_helpers);
    TM_RUN_TEST(test_mcp_app_content_adapter_registry_is_generic);
    TM_RUN_TEST(test_mcp_app_cesium_adapter_is_isolated_and_declares_csp);
    TM_RUN_TEST(test_es256_jwt_derive_public_key_matches_rfc6979);
    TM_RUN_TEST(test_es256_jwt_pkcs8_build_and_verify);
    TM_RUN_TEST(test_es256_jwt_sec1_build_and_verify);
    TM_RUN_TEST(test_es256_jwt_tamper_detected);
    TM_RUN_TEST(test_es256_jwt_invalid_pem_rejected);
    TM_RUN_TEST(test_es256_jwt_claims_times_and_jti);

    TmTestRunner::instance().printSummary();
    return TmTestRunner::instance().hasFailed() ? 1 : 0;
}
